shellEmulator: true

trustPolicy: no-downgrade
trustPolicyExclude:
  - chokidar@4.0.3

packages:
  - packages/**
  - playground/*
ignoredBuiltDependencies:
  - core-js
onlyBuiltDependencies:
  - esbuild
  - vue-demi
